[package]
name = "techr-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "techr"
crate-type = ["cdylib", "rlib"]

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
